services:
  test:
    build: .
    image: rick-morty-newman:latest
    volumes:
      - ./reports:/app/reports

  test-report:
    build: .
    image: rick-morty-newman:latest
    command: npm test
    volumes:
      - ./reports:/app/reports
    profiles:
      - report

  docs-serve:
    build: .
    image: rick-morty-newman:latest
    command: npm run docs:serve
    ports:
      - "3000:3000"
    profiles:
      - docs
