services:
  test:
    build: .
    image: rick-morty-newman:latest
    volumes:
      - ./reports:/app/reports
    command: npm test

  docs:
    build: .
    image: rick-morty-newman:latest
    ports:
      - "3000:3000"
    volumes:
      - ./reports:/app/reports
    command: npx docusaurus serve --port 3000 --dir build
